### ISSUE TITLE
#PI-III-01 - Descrição da Equipe

### ISSUE THREAD

**Issue by ProfCarlosVerissimo** [JizreelMess/PI_3_2022_GR02#1]
# Objetivo
* Descrevam aqui:
    * Tema do trabalho (exemplo: App para adoção de PETs"
    * Breve descrição da situação problema (exemplo: Desenvolver um app para facilitar a adoção de Pets, tendo  como objetivo subjacente a criação de uma rede social com pessoas interessadas em cuidar de animais de estimação)
 
# Artefatos
Deverá ser postado **um arquivo**, formato PDF, cujo conteúdo deverá ter:
* Scrum Master 
    * Nome
    *  Responsabilidades
* Product Owner
    * Nome
    * Responsabilidades 
* Development Time
    Nome | papel | Responsabilidade 
    --------| ------ |--------------------
     xxx      |          |                               
     yyy      |          |                              
     zzz      |          |

**Comment by JizreelMess** [comment]
Objetivo

      (Aplicativo voltado para reunir todas as informações do pet, dados e ficha medica).

 Desenvolvimento de um aplicativo focado em facilita o acesso medico para pets, aonde as informações do seu animal de estimação estejam a todo momento disponivel, ficha medica completa, informações do dono e seu pet. 
Criando uma conexão entre ongs, clinicas veterinárias e pessoas que possui animais de estimação.

[Artefato.pdf](https://github.com/JizreelMess/PI_3_2022_GR02/files/8164443/Artefato.pdf)

**Comment by ProfCarlosVerissimo** [comment]
Muito Obrigado pelo retorno
